AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Smartwatch IoT → MQTT → IoT Rule → Default EventBridge Bus → Pipe → SNS Email
  Now includes Kinesis Data Stream as source.

Resources:

  SmartwatchSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: smartwatch-alerts

  SmartwatchSNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: bmangwale@gmail.com
      TopicArn: !Ref SmartwatchSNSTopic

  # IoT Rule Role
  IoTRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: IoTRulePutEventsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: "*"

  # IoT Topic Rule sending to EventBridge
  SmartwatchIoTRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: SmartwatchIoTRule
      TopicRulePayload:
        Sql: "SELECT * FROM 'smartwatch/topic'"
        AwsIotSqlVersion: "2016-03-23"
        RuleDisabled: false
        Actions:
          - EventBridge:
              RoleArn: !GetAtt IoTRuleRole.Arn
              EventBusName: default

  # Kinesis Data Stream
  SmartwatchKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: smartwatch-stream
      ShardCount: 1
      RetentionPeriodHours: 24

  # Pipe: Kinesis → SNS
  SmartwatchEventPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      RoleArn: !GetAtt PipeRole.Arn
      Source: !GetAtt SmartwatchKinesisStream.Arn
      SourceParameters:
        KinesisStreamParameters:
          BatchSize: 100
          MaximumBatchingWindowInSeconds: 60
      Target: !Ref SmartwatchSNSTopic

  PipeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: pipes.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PipePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref SmartwatchSNSTopic
              - Effect: Allow
                Action:
                  - kinesis:GetRecords
                  - kinesis:GetShardIterator
                  - kinesis:DescribeStream
                  - kinesis:ListShards
                Resource: !GetAtt SmartwatchKinesisStream.Arn
